/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1.3-35-g419cdf9dcc-20260129"
#endif /* AVUTIL_FFVERSION_H */
